Data_Analysis_Challenge_Data_Set
library(readr)
Data_Analysis_Challenge_Data_Set <- read_csv("C:/Users/Prakash/Desktop/Data Analysis Challenge Data Set.csv")
 View(Data_Analysis_Challenge_Data_Set)
 attach(Data_Analysis_Challenge_Data_Set)
summary(`wheel-base`)
 summary(length)
 summary(width)
 summary(height)
 summary(`curb-weight`)
 summary(`engine-size`)
 summary(bore)
 summary(stroke)
 summary(`compression-ratio`)
 summary(horsepower)
 summary(`peak-rpm`)
 summary(`city-mpg`)
 summary(`highway-mpg`)
 sd(`wheel-base`)
 sd(length)
 sd(width)
 sd(height)
 sd(`curb-weight`)
 sd(`engine-size`)
 sd(`compression-ratio`)
 sd(`city-mpg`)
 sd(`highway-mpg`)
 hist(Data_Analysis_Challenge_Data_Set$`wheel-base`)
 hist(Data_Analysis_Challenge_Data_Set$length)
 hist(Data_Analysis_Challenge_Data_Set$width)
 hist(Data_Analysis_Challenge_Data_Set$height)
 hist(Data_Analysis_Challenge_Data_Set$`curb-weight`)
 hist(Data_Analysis_Challenge_Data_Set$`engine-size`)
 hist(Data_Analysis_Challenge_Data_Set$`compression-ratio`)
 hist(Data_Analysis_Challenge_Data_Set$`city-mpg`)
 hist(Data_Analysis_Challenge_Data_Set$`highway-mpg`)
 hist(Data_Analysis_Challenge_Data_Set$`compression-ratio`)
 library(plm)
 mydata<-read.csv("C:/Users/Prakash/Desktop/Data Analysis Challenge Data Set.csv")
 attach(mydata)
 X<-cbind(length,width,height)
 pdata<-plm.data(mydata, index=c("symboling"))
 Y<- cbind(`curb-weight`)
 summary(Y)
 summary(X)
 pooling<-plm(Y~X,data=pdata,model="pooling")
 summary(pooling)
 between<-plm(Y~X,data=pdata,model="between")
 summary(between)
 FirstDifference<-plm(Y~X,data=pdata,model="fd")
 summary(FirstDifference)
 WithinEstimator<-plm(Y~X,data=pdata,model="within")
 summary(WithinEstimator)
 RandomEffects<-plm(Y~X,data=pdata,model="random")
 summary(RandomEffects)
 plmtest(pooling)
 pFtest(FirstDifference,pooling)
 phtest(RandomEffects,FirstDifference)

 